config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  root to: "products#index"
  post "product/:permalink", to: "products#buy"
  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]

  get "/homepage/index" => 'homepage#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	 before_filter(:except => :status) { redirect_to root_path unless has_order? }

  def destroy
    current_order.destroy
    session[:order_id] = nil
    respond_to do |wants|
      wants.html { redirect_to root_path, :notice => "Your basket has been emptied successfully."}
      wants.json do
        flash[:notice] = "Your shopping bag is now empty."
        render :json => {:status => 'complete', :redirect => root_path}
      end
    end
  end
	
	def checkout
	  @order = Shoppe::Order.find(current_order.id)
	  if request.patch?
	    if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
	      redirect_to checkout_payment_path
	    end
	  end
	end

def payment
  @order = Shoppe::Order.find(session[:order_id])
  if request.post?
    if @order.accept_stripe_token(params[:stripe_token])
      redirect_to checkout_confirmation_path
    else
      flash.now[:notice] = "Could not exchange Stripe token. Please try again."
    end
  end
end	

	def confirmation
	  if request.post?
	    current_order.confirm!
	    session[:order_id] = nil
	    redirect_to root_path, :notice => "Order has been placed successfully!"
	  end
	end

	def remove_item
	    item = current_order.order_items.find(params[:order_item_id])
	    if current_order.order_items.count == 1
	      destroy
	    else
	      item.remove
	      respond_to do |wants|
	        wants.html { redirect_to request.referer, :notice => "Item has been removed from your basket successfully"}
	        wants.json do
	          current_order.reload
	          render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
	        end
	      end
	    end
	  end

	def change_item_quantity
		item = current_order.order_items.find(params[:order_item_id])
		request.delete? ? item.decrease! : item.increase!
		respond_to do |wants|
		  wants.html { redirect_to request.referer || root_path, :notice => "Quantity has been updated successfully." }
		  wants.json do
		    current_order.reload
		    if current_order.empty?
		      destroy
		    else
		      render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
		    end
		  end
		end    
		rescue Shoppe::Errors::NotEnoughStock => e
		respond_to do |wants|
		  wants.html { redirect_to request.referer, :alert => "Unfortunately, we don't have enough stock. We only have #{e.available_stock} items available at the moment. Please get in touch though, we're always receiving new stock." }
		  wants.json { render :json => {:status => 'error', :message => "Unfortunateley, we don't have enough stock to add more items."} }
		end
	end

	  def change_delivery_service
    if current_order.delivery_service = current_order.available_delivery_services.select { |s| s.id == params[:delivery_service].to_i}.first
      current_order.save
      respond_to do |wants|
        wants.html { redirect_to request.referer, :notice => "Delivery service has been changed"}
        wants.json do
          current_order.reload
          render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
        end
      end
    else
      respond_to do |wants|
        wants.html { redirect_to request.referer, :alert => "You cannot select this delivery method."}
        wants.json { render :json => {:status => 'error', :message => 'InvalidDeliveryMethod'}, :status => 422 }
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Shoppe::Product.active.includes(:product_categories, :variants).root
    @products = @products.group_by(&:product_category)
  end

  def show
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
    @product_attributes = Shoppe::ProductAttribute.where(product_id: @product.id)
    respond_to do |format|
        format.html
        format.json { render :json => {:product => @product, :attributes => @product_attributes}  }
    end
  end

	def buy
	  @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
	  current_order.order_items.add_item(@product, 1)
	  redirect_to :back , :notice => "Product has been added successfuly!"
	    rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "We're sorry but we don't have enough stock to add that many products. We currently have #{e.available_stock} item(s) in stock. Please try again."}
      wants.json { render :json => {:error => 'NotEnoughStock', :available_stock => e.available_stock}}
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/homepage/index.html.erb
<div id="homepage" class="">
	<div class="top-section">
		<div class="container-fluid">
			<div style="min-height: 450px;"class="row">
				<div class="col-sm-offset-3 col-md-8">
					<h2 class="homepage-center-text">Who delivers in your neighborhood?</h2>
					<p style="">You do. Pickup in your neighborhood.</p>
					<select style="">
					  <option value="1">Elm City Market, New Haven, CT</option>
					</select>
					<%= button_to( 'bento', root_path, :method => :get, :class => 'logo-title', :style => "background-color: #61dff0; color:white; border: none " )  %> 
				</div>
			</div>
		</div>
	</div>

	<div class="bottom-section">
		<div style="color: black" class="container-fluid">
			<div class="row">
				<div style="text-align: center; font-size: 2em; font-weight: 300; padding-top: 20px;" class="col-sm-offset-3 col-sm-6">
					<p style="margin-bottom: 0px; font-weight: 300">Who are we?</p>
					<span style="font-size: .75em; ">Ordering from your favorite restaurant is even easier than eating.<span>
					<%= render :partial => '/shared/mailchimp'%>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag "normalize.css" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => '/shared/wrapbootstrap_header'%>

  <% if notice || alert %>
    <div class="row">
      <% if notice || alert %>
        <div class="flash_messages">
          <%= raw "<div data-alert class='alert-box warning'> #{notice} <a href='' class='close'>&times;</a></div>"  if notice %>
          <%= raw "<div data-alert class='alert-box alert'>#{alert} <a href='' class='close'>&times;</a></div>"     if alert %>
        </div>
      <% end %>
    </div>
  <% end %>
<% if false %>
<% if current_order %>
<p style="border:1px solid black;padding:10px;">
  You have <%= pluralize current_order.total_items, 'item'%> in your basket which cost
  <%= number_to_currency current_order.total_before_tax %>.
</p>
<%= link_to "View basket", basket_path %>
<%= link_to "Checkout", checkout_path %>
<% end%>

<%= flash[:notice] %>
<% end %>


<%= yield %>

</body>
</html>

app/views/orders/_items.html.erb
<table id="checkout-table" width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td style="font-weight: 600">
        <%= item.quantity %>
        <% unless defined?(readonly) %>
          <span>
            <%= link_to "+", adjust_basket_item_quantity_path(item.id), :method => :post, :class => 'ajax' %>
            <%= link_to "-", adjust_basket_item_quantity_path(item.id), :method => :delete, :class => 'ajax' %>
          </span>
        <% end %>
      </td>
      <td>
        <%= link_to item.ordered_item.full_name, product_path(item.ordered_item.permalink) %>
        <% unless defined?(readonly) %>
          <%= link_to "Delete", remove_basket_item_path(item), :method => :delete, :class => 'delete ajax' %>
        <% end %>
      </td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
      <tr class="delivery">
        <td class="method" colspan="4">
          <% if defined?(readonly) %>
            <%= order.delivery_service.name %>
          <% else %>
            <%= form_tag change_delivery_service_path do  %>
              <%= select_tag 'delivery_service', options_from_collection_for_select(order.available_delivery_services, :id, :name, order.delivery_service.id) %>
            <% end %>
          <% end %>
        </td>
        <td class="money">
          <%= number_to_currency order.delivery_price %>
        </td>
      </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='4'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/checkout.html.erb
<div class="container">
    <h2>Place Your Order</h2>
    <p>Fantastic! You're ready to place your order, just follow the instructions below and we'll get your products shipped to you as quickly as we can.</p>
    <p>Complete your details below to complete your order</p>

    <div class="row">
        <%= form_for @order, :url => checkout_path do |f| %>
            <dl class="col-md-4">
                <dt><%= f.label :first_name, 'First Name*' %></dt>
                <dd><%= f.text_field :first_name, :required => true %></dd> 

                <dt><%= f.label :last_name, 'Last Name*' %></dt>
                <dd><%= f.text_field :last_name, :required => true  %></dd>
                <dt><%= f.label :email_address %></dt>
                <dd><%= f.text_field :email_address %></dd>

                <dt><%= f.label :phone_number %></dt>
                <dd><%= f.text_field :phone_number %></dd>
            </dl>
                <dl class="col-md-4">
                <dt><%= f.label :billing_address1, 'Address1*' %></dt>
                <dd><%= f.text_field :billing_address1, :required => true  %></dd>
                <dt><%= f.label :billing_address2, 'Address2 (optional)' %></dt>
                <dd><%= f.text_field :billing_address2 %></dd>
                <dt><%= f.label :billing_address3, 'City*' %></dt>
                <dd><%= f.text_field :billing_address3, :required => true  %></dd>
                <dt><%= f.label :billing_address4, 'State*' %></dt>
                <dd><%= f.text_field :billing_address4, :required => true  %></dd>
                <dt><%= f.label :billing_postcode, 'Post Code*' %></dt>
                <dd><%= f.text_field :billing_postcode, :required => true  %></dd>
                <dt><%= f.label :billing_country_id, 'Country*'%></dt>
                <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true, :required => true  %></dd>
                <dd>
            </dl>
          <div class="col-md-4">  
            
            <h3>Order Summary</h3>

            <table>
              <tbody>
                <tr>
                  <td><strong>Sub-Total:</strong></td>
                  <td><strong><%= number_to_currency @order.total_before_tax %></strong></td>
                </tr>
                </tbody><tbody>
                </tbody>
                <tbody><tr>
                  <td><strong>Total:</strong></td>
                  <td><strong><span><%= number_to_currency @order.total %></span></strong></td>
                </tr>
              </tbody>
            </table>

            <%= f.submit 'Continue' %></dd>
            <% end %>

          </div>


    </div>

    <!-- <p>Review the products in your shopping bag</p> -->
    <% if false %>
    <%= render 'items', :order => @order %>
    <% end %>
</div> 

app/views/orders/confirmation.html.erb
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order" %>

app/views/orders/payment.html.erb
<div class="container">
<%= shoppe_stripe_javascript %>

<h2>Pay using your credit/debit card</h2>

<%= form_tag nil, class: "stripeForm" do %>
  <%= hidden_field_tag "stripe_token", nil, "data-stripe" => "token" %>
  <dl>
    <dt><%= label_tag 'card_number' %></dt>
    <dd><%= text_field_tag 'card_number', nil, name: nil, "data-stripe" => "number" %></dd>
    <dt><%= label_tag 'expiry_month' %></dt>
    <dd style="display: inline"><%= text_field_tag 'expiry_month', nil, name: nil, "data-stripe" => "exp-month"%></dd>
    <dd style="display: inline"><%= text_field_tag 'expiry_year', nil, name: nil, "data-stripe" => "exp-year" %></dd>
    <dt><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code', nil, name: nil, "data-stripe" => "cvc" %></dd>
  </dl>
  <%= submit_tag "Continue" %>
<% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
	<span> Shopping Cart </span>
	<%= render 'items', :order => current_order %>
	<div class="group-buttons">
		<%= button_to 'Empty basket', basket_path, :method => :delete %>
		<%= button_to( 'Continue Shopping', root_path)  %> 
		<%= button_to "Checkout", checkout_path, :method => :get, :style => "float: right"  %>
	</div>
</div>

app/views/products/index.html.erb
<div id="product-index" class="container-fluid">
  <div class="row">
    <div class="col-md-3 preview-pane">
        <center style="color: white" ng-app="flapperNews" ng-controller="MainCtrl">{{test}}</center>
        <img src="/assets/grubhub">
    </div>
    <div class="col-md-8">
      <h1>Mealkits</h1>
      <% @products.each do |category, products| %>
      <% products.each do |product| %>

      <div style="display: inline-block" class="grid-item">
        <div style="position:relative">
          <span> <%= number_to_currency product.price %> </span>
          <% if product.default_image %>
          <%= link_to image_tag(product.default_image.path, :size => "200x200", :class=> "product-image"), product_path(product.permalink) %>
          <% end %>
          <p><%= product.name %></p>
          <%= button_to "Add to basket", product_path(product.permalink), :method => :post %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<button id='test'></button>

<script>
$('#test').click(function(){
  $.ajax({
        type: "GET",
        dataType: "json",
        url: "/product/yaki-linguine",
        success: function(data){
          console.log(data)
        }
    }); 
} )


</script>

app/views/products/show.html.erb
<div id="product-show" class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-1 col-md-6">
			<% if @product.default_image %>
		  		<%= image_tag @product.default_image.path, :style => "margin: auto; display: block; max-width: 450px" %>
			<% end %>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-xs-12">
	              <h1 class="tier">Basic</h1>
	            </div>
			</div>
			<h2><%= @product.name %></h2>
			<h1><%= number_to_currency @product.price %></h1> 
			<%= simple_format @product.description %>
			<%= button_to "Add to basket", product_path(@product.permalink), :method => :post, :style => "float: right;" %>
		</div>
	</div>
</div>

app/views/shared/_mailchimp.html.erb
											<!-- Begin MailChimp Signup Form -->
						<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
						<style type="text/css">
							#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
							/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
							   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
						</style>
						<div id="mc_embed_signup">
						<form action="//heroku.us13.list-manage.com/subscribe/post?u=e7f1ad9b5f3af557e03afc061&amp;id=ac726813e4" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
						    <div id="mc_embed_signup_scroll">
							
						<div class="mc-field-group">
							<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
						</label>
							<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
						</div>
							<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div>
							</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
						    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e7f1ad9b5f3af557e03afc061_ac726813e4" tabindex="-1" value=""></div>
						    <div style="float:right" class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
						    </div>
						</form>
						</div>
						<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
						<!--End mc_embed_signup-->

app/views/shared/_wrapbootstrap_header.html.erb
<nav class="wrap-nav">
	<div class="container">
		<div class="row">
			<%= link_to( 'bento', root_path, :class => 'logo-title' )  %> 

			<div class="cart">
			  <%= link_to image_tag("shopping.svg", :size => "30x40", :border => 0, :alt => '', :title => '', :class => 'dropbtn'), basket_path %> 
			  <% if has_order? && current_order.has_items? %>
			    	<span class="mainNavCart-itemQty"> <%=current_order.total_items%> </span>
			  <% end %>
			</div>
		</div>
	</div>
</nav>